# Generated by Django 5.1.1 on 2025-04-19 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('Hotel', 'Diskon Hotel 30%'), ('Travel', 'Voucher Travel Rp100.000'), ('Photobooth', 'Paket Photobooth Gratis'), ('Food', 'Voucher Makan Rp50.000'), ('Transport', 'Diskon Transport 25%'), ('Souvenir', 'Paket Souvenir Wisata'), ('Adventure', 'Tur Petualangan Diskon')], max_length=50)),
                ('code', models.CharField(blank=True, max_length=10, unique=True)),
                ('points_required', models.PositiveIntegerField(default=2000)),
                ('is_redeemed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
