# Generated by Django 5.1.1 on 2025-04-19 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='brand',
            field=models.CharField(choices=[('Hotel', 'Diskon Hotel 30%'), ('Travel', 'Voucher Travel Rp100.000'), ('Photobooth', 'Paket Photobooth Gratis'), ('Food', 'Voucher Makanan Rp50.000'), ('Transport', 'Diskon Transportasi 25%'), ('Souvenir', 'Paket Souvenir Wisata'), ('Adventure', 'Diskon Tur Petualangan'), ('Spa', 'Diskon Spa & Refleksi 20%'), ('Cinema', 'Beli 1 Gratis 1 Tiket Bioskop'), ('Museum', 'Tiket Museum Gratis'), ('ThemePark', 'Voucher Taman Hiburan 2×1'), ('Waterpark', 'Diskon Waterpark 30%'), ('CoffeeShop', 'Voucher Kopi Gratis'), ('Bakery', 'Diskon 15% Roti & Kue'), ('Gym', 'Uji Coba Gym Gratis 1 Minggu'), ('YogaStudio', 'Kelas Yoga Gratis 1×1'), ('ArtGallery', 'Diskon Masuk Galeri Seni'), ('BoatTour', 'Diskon Tur Perahu 25%'), ('Zoo', 'Tiket Masuk Kebun Binatang Gratis'), ('Aquarium', 'Diskon Aquarium 2×1'), ('Camping', 'Diskon Sewa Perlengkapan Berkemah'), ('Surfing', 'Diskon Kursus Selancar 50%'), ('Cooking', 'Kelas Memasak Gratis'), ('WineTasting', 'Voucher Wine Tasting'), ('CarRental', 'Diskon Sewa Mobil 20%'), ('BikeRental', 'Diskon Sewa Sepeda 30%'), ('PaddleBoard', 'Paddle Boarding Gratis 1 Jam'), ('PhotoPrints', 'Cetak Foto Beli 10 Gratis 1'), ('Bookstore', 'Voucher Toko Buku Rp75.000'), ('BakeryCafe', 'Diskon Kue & Kopi 20%'), ('IceCream', 'Es Krim Cone Gratis'), ('Salon', 'Diskon Salon & Perawatan Rambut 30%'), ('CinemaVIP', 'Diskon 2×1 Bioskop VIP'), ('FlowerShop', 'Diskon Bunga 25%'), ('GiftShop', 'Voucher Toko Oleh-oleh'), ('EscapeRoom', 'Diskon Escape Room 15%'), ('Karaoke', 'Diskon Karaoke 2 Jam'), ('Bowling', 'Diskon Bowling 50%'), ('Paintball', 'Diskon Paintball 20%')], max_length=50),
        ),
    ]
