# Generated by Django 5.2 on 2025-04-15 15:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(error_messages={'unique': 'A user with that email already exists.'}, max_length=254, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(help_text='4-30 characters. Letters, numbers, dots (.), and underscores (_) only.', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Username must be 4-30 characters long and can only contain letters, numbers, dots, and underscores.', regex='^[a-zA-Z0-9_.]{4,30}$')]),
        ),
    ]
