# Generated by Django 5.2 on 2025-04-18 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('google_maps_link', models.URLField()),
                ('description', models.TextField()),
                ('photo_main', models.ImageField(upload_to='places/')),
                ('photo_1', models.ImageField(blank=True, null=True, upload_to='places/')),
                ('photo_2', models.ImageField(blank=True, null=True, upload_to='places/')),
                ('photo_3', models.ImageField(blank=True, null=True, upload_to='places/')),
            ],
        ),
    ]
